export const CHUCK_FACTS = {
  SEARCH_FACTS: 'SEARCH_FACTS',
  SEARCH_FACTS_SUCCESS: 'SEARCH_FACTS_SUCCESS',
  SEARCH_FACTS_REQUEST: 'SEARCH_FACTS_REQUEST',
  SEARCH_FACTS_FAILURE: 'SEARCH_FACTS_FAILURE',
};
